# --------------
# -- Settings --
# --------------

title: Media Map
description: >-
  A map of locations featured in movies, tv shows, and books!
baseurl: ""
url: "https://mediamap.nyc"

# Should compress with TinyPNG
images:
  favicon: "/images/favicon.ico"
  hero: "/images/hero-image.png"
  profile: "/images/profile.svg"
  # seo: "/images/seo.png"

# Build settings
theme: minima

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
