# --------------
# -- Settings --
# --------------

title: Media Map
description: >-
  A map of locations featured in movies, TV shows, and books!
baseurl: ""
url: "https://mediamap.nyc"

# PNGs compressed with TinyPNG
images:
  favicon: "/images/favicon.ico"
  profile: "/images/profile.svg"
  # seo: "/images/seo.png"

# Build settings
theme: minima

defaults:
  - scope:
      path: "images/media"
    values:
      image: true

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
