# --------------
# -- Settings --
# --------------

title: Media Map
description: >-
  A map of locations featured in movies, TV shows, and books!
baseurl: ""
url: "https://mediamap.nyc"

# PNGs compressed with TinyPNG
images:
  favicon: "/images/favicon.ico"
  profile: "/images/profile.svg"
  # seo: "/images/seo.png"

featured:
  - name: "Sex and the City"
    link: "/images/media/TV/Sex and the City/SATC-TV.png"

  - name: "Gossip Girl"
    link: "/images/media/TV/Gossip Girl/GSPGRL-TV.png"

  - name: "Sopranos"
    link: "/images/media/TV/Sopranos/SPRNOS-TV.png"

  - name: "Friends"
    link: "/images/media/TV/Friends/FRNDS-TV.png"

  - name: "Catcher in the Rye"
    link: "/images/media/LIT/Catcher in the Rye/CITR-LIT.png"

  - name: "Just Kids"
    link: "/images/media/LIT/Just Kids/JK-LIT.png"
    
  - name: "The Great Gatsby"
    link: "/images/media/LIT/The Great Gatsby/TGG-LIT.png"

  - name: "Spiderman"
    link: "/images/media/FILM/Spiderman/SPDR1-FILM.png"

  - name: "The Godfather"
    link: "/images/media/FILM/The Godfather/GDFTHR-FILM.png"

  - name: "When Harry Met Sally"
    link: "/images/media/FILM/When Harry Met Sally/WHMS-FILM.png"


# Build settings
theme: minima

defaults:
  - scope:
      path: "images/media"
    values:
      image: true

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
